# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{colour}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wes Devauld"]
  s.date = %q{2011-09-07}
  s.description = %q{Support for computation of colour swatches in both the RGB and HSV colour representations}
  s.email = %q{wes@devauld.ca}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.txt"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "lib/colour.rb",
    "lib/gradient.rb",
    "lib/hsv.rb",
    "lib/rgb.rb",
    "lib/standard_colours.rb",
    "spec/gradient_spec.rb",
    "spec/hsv_spec.rb",
    "spec/rgb_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/color_representation.rb"
  ]
  s.homepage = %q{http://github.com/wdevauld/colour}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Colour manipulation library supporting RGB and HSV representations}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rspec>, ["~> 2.6"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rspec>, ["~> 2.6"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

